version: '3'

services:
  db:
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moto
    volumes:
      - ./db/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql